github:
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
  mappers:
  - '|paketobuildpacks|paketo-buildpacks|'
  - '|paketocommunity|paketo-community|'

codeowners:
- path:  "*"
  owner: "@paketo-community/rust-maintainers"

package:
  repositories:   ["docker.io/paketocommunity/rust"]
  register:       true
  registry_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

docker_credentials:
- registry: docker.io
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}
