github:
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
  mappers:
  - '|paketocommunity|paketo-community|'

codeowners:
- path:  "*"
  owner: "@paketo-community/rust-maintainers"

package:
  repositories:   ["docker.io/paketobuildpacks/rust","gcr.io/paketo-buildpacks/rust"]
  register:       true
  registry_token: ${ secrets.PAKETO_BOT_GITHUB_TOKEN }

docker_credentials:
- registry: gcr.io
  username: _json_key
  password: ${{ secrets.GCR_PUSH_BOT_JSON_KEY }}
- registry: docker.io
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}
