description = "A sample Builder for using Rust related CNBs"

[[buildpacks]]
  id = "paketo-community/rust-dist"
  uri = "docker://paketocommunity/rust-dist:0.0.13"

[[buildpacks]]
  id = "paketo-community/cargo-install"
  uri = "docker://paketocommunity/cargo-install:0.0.9"

[[buildpacks]]
  id = "paketo-buildpacks/procfile"
  uri = "docker://gcr.io/paketo-buildpacks/procfile:4.2.2"

[[order]]

group = [
    { id = "paketo-community/rust-dist", version="0.0.13"},
    { id = "paketo-community/cargo-install", version="0.0.9"},
    { id = "paketo-buildpacks/procfile", version="4.2.2", optional=true},
]

[stack]
  id = "io.buildpacks.stacks.bionic"
  build-image = "gcr.io/paketo-buildpacks/build:base-cnb"
  run-image = "gcr.io/paketo-buildpacks/run:base-cnb"

# Swap the stack if you want more packages
# [stack]
#   id = "io.buildpacks.stacks.bionic"
#   build-image = "gcr.io/paketo-buildpacks/build:full-cnb-cf"
#   run-image = "gcr.io/paketo-buildpacks/run:full-cnb-cf"

# Swap the stack if you want less packages
# [stack]
#   id = "io.paketo.stacks.tiny"
#   build-image = "gcr.io/paketo-buildpacks/build:tiny-cnb"
#   run-image = "gcr.io/paketo-buildpacks/run:tiny-cnb"
