description = "A sample Builder for using Rust related CNBs"

[[buildpacks]]
  id = "paketo-community/rustup"
  uri = "docker://paketocommunity/rustup:1.0.0"

[[buildpacks]]
  id = "paketo-community/rust-dist"
  uri = "docker://paketocommunity/rust-dist:1.1.0"

[[buildpacks]]
  id = "paketo-community/cargo"
  uri = "docker://paketocommunity/cargo:0.0.12"

[[buildpacks]]
  id = "paketo-buildpacks/procfile"
  uri = "docker://gcr.io/paketo-buildpacks/procfile:4.3.1"

[[order]]

group = [
    { id = "paketo-community/rustup", version="1.0.0"},
    { id = "paketo-community/rust-dist", version="1.1.0"},
    { id = "paketo-community/cargo", version="0.0.12"},
    { id = "paketo-buildpacks/procfile", version="4.3.1", optional=true},
]

[stack]
  id = "io.buildpacks.stacks.bionic"
  build-image = "gcr.io/paketo-buildpacks/build:base-cnb"
  run-image = "gcr.io/paketo-buildpacks/run:base-cnb"

# Swap the stack if you want more packages
# [stack]
#   id = "io.buildpacks.stacks.bionic"
#   build-image = "gcr.io/paketo-buildpacks/build:full-cnb-cf"
#   run-image = "gcr.io/paketo-buildpacks/run:full-cnb-cf"

# Swap the stack if you want less packages
# [stack]
#   id = "io.paketo.stacks.tiny"
#   build-image = "gcr.io/paketo-buildpacks/build:tiny-cnb"
#   run-image = "gcr.io/paketo-buildpacks/run:tiny-cnb"
